### ISSUE TITLE
Shifting window function

### ISSUE THREAD

**Issue by ercbk** [DavisVaughan/slider#109]
``` r
date <- as.Date("2020-06-21") + seq(0, 13)
positives <- c(0, 0, 0, 0, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1)
num_tests <- c(3, 29, 83, 22, 94, 50, 15,  4, 31, 53, 29, 50, 6, 11)

df <- tibble::tibble(date, positives, num_tests)
df
#> # A tibble: 14 x 3
#>    date       positives num_tests
#>    <date>         <dbl>     <dbl>
#>  1 2020-06-21         0         3
#>  2 2020-06-22         0        29
#>  3 2020-06-23         0        83
#>  4 2020-06-24         0        22
#>  5 2020-06-25         1        94
#>  6 2020-06-26         1        50
#>  7 2020-06-27         2        15
#>  8 2020-06-28         0         4
#>  9 2020-06-29         1        31
#> 10 2020-06-30         1        53
#> 11 2020-07-01         1        29
#> 12 2020-07-02         1        50
#> 13 2020-07-03         1         6
#> 14 2020-07-04         1        11
```
I just want to two calculations.
1. from 6/21 to 6/27 and 2. from 6/28 to 7/04
From what I can tell from your documentation, I think I need .step, but I can't get it to work. Here's the calculation I'm trying to run.

```r
slider::slide2_dbl(df$positive, df$num_tests, .step = 6, .f = ~sum(.x)/sum(.y))
```
Also, what's an mweek and a yweek?
Thanks.

**Comment by DavisVaughan** [comment]
`slide_*()` functions always return a vector that is the same length as `.x`. So it will always have length 14 here.

Instead, it looks like you want the `hop_*()` equivalent that allows you to manually specify start and stop points for your window.

Because this is relative to a date _index_, you should also use the index functions, i.e. `slide_index2()` and `hop_index2()`, rather than just `slide2()`.

So it looks like you want something like this

``` r
library(slider)
library(tibble)

date <- as.Date("2020-06-21") + seq(0, 13)
positives <- c(0, 0, 0, 0, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1)
num_tests <- c(3, 29, 83, 22, 94, 50, 15,  4, 31, 53, 29, 50, 6, 11)

df <- tibble(date, positives, num_tests)

stops <- as.Date(c("2020-06-27", "2020-07-04"))
starts <- stops - 6

result <- tibble(
  starts = starts,
  stops = stops
)

result$result <- hop_index2_vec(
  .x = positives, 
  .y = num_tests, 
  .i = date, 
  .starts = starts, 
  .stops = stops, 
  .f = ~sum(.x) / sum(.y),
  .ptype = double()
)

result
#> # A tibble: 2 x 3
#>   starts     stops      result
#>   <date>     <date>      <dbl>
#> 1 2020-06-21 2020-06-27 0.0135
#> 2 2020-06-28 2020-07-04 0.0326
```

<sup>Created on 2020-07-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

An mweek and yweek are specific to the `.period` argument of `slide_period()`. These are inherited from `?warp::warp_distance()` so I would encourage you to look there for the full documentation. These are fully described in the `Period` section of the help documentation of that function. I tried to make it clear at the top of `?slide_period` that you should look there, but perhaps that wasn't explicit enough.

Essentially mweek lets you group by the "week of the month" and yweek lets you group by "week of the year"

https://davisvaughan.github.io/warp/reference/warp_distance.html#period

**Comment by ercbk** [comment]
Looks great, Davis.
Re yweek, etc., I looked everywhere, but there. It was late.
Thank you
