### ISSUE TITLE
Why not set the null value to NA? It is easier  to keep the sample size matched.

### ISSUE THREAD

**Issue by MatixR** [DavisVaughan/slider#154]
When calcultate the rolling-window statistics,  it is hard to keep size matched with the size of  original data, especially in slide_dfr()  with user-defined functions.

For example:

`
test_rollingreg_04 <- pedestrian   %>%
   group_by_key() %>%
   slice(1:500) %>%
   group_by(Sensor) %>%
   nest() %>%
   mutate(
     ols_model = map(    # althouth it is not necessary usually,  it is usefull  with multi processors.
       data,
      ~slide_dfr(
       .,
       ols_results,
       .before = 99,
       .complete = F))    # if choose T, then is hard to match the observation one by one
   )

 # multiple outputs
 ols_results <- function(...) {
   data <- as_tibble(...)

   fit <- lm(Count ~ Time, data = data)
   beta  <- coefficients(fit)[[2]]
   alpha <- coefficients(fit)[[1]]

   # beta = beta
   # alpha = alpha
   tibble(beta,alpha)
 }
`

**Comment by DavisVaughan** [comment]
Two things to help you understand here:

- We always use `NULL` as the missing value for list elements, because that is what vctrs does too.
- `slide_dfr()` and `slide_dfc()` don't have the size guarantee that `slide()` and all the other variants do. It is implemented as as `slide()` + `vctrs::vec_rbind()`, so its possible to return more or less elements than `x` if any list element doesn't have an element that is size 1. This is in line with purrr.
``` r
library(slider)
library(tibble)

slide(1:4, ~tibble(x = .x), .before = 2)
#> [[1]]
#> # A tibble: 1 x 1
#>       x
#>   <int>
#> 1     1
#> 
#> [[2]]
#> # A tibble: 2 x 1
#>       x
#>   <int>
#> 1     1
#> 2     2
#> 
#> [[3]]
#> # A tibble: 3 x 1
#>       x
#>   <int>
#> 1     1
#> 2     2
#> 3     3
#> 
#> [[4]]
#> # A tibble: 3 x 1
#>       x
#>   <int>
#> 1     2
#> 2     3
#> 3     4

# just row binds the results from above
slide_dfr(1:4, ~tibble(x = .x), .before = 2)
#> # A tibble: 9 x 1
#>       x
#>   <int>
#> 1     1
#> 2     1
#> 3     2
#> 4     1
#> 5     2
#> 6     3
#> 7     2
#> 8     3
#> 9     4

# see, result isn't size 4 here either
purrr::map_dfr(1:4, ~tibble(x = sample(.x)))
#> # A tibble: 10 x 1
#>        x
#>    <int>
#>  1     1
#>  2     2
#>  3     1
#>  4     3
#>  5     1
#>  6     2
#>  7     3
#>  8     4
#>  9     1
#> 10     2
```

If you can guarantee that each tibble you are trying to return from `ols_results()` only has 1 row (and it looks like that is the case for you), then you should use `slide_vec()`. This has the same size guarantee that `slide()` and `slide_dbl()` do, but can return any data type. You can specify a `.ptype` directly as an argument to specify the output type, but it will otherwise be guessed automatically. I expect that purrr will eventually get a `map_vec()` function that works similar to this one.

``` r
library(slider)
library(tidyverse)
library(tsibble)

ols_results <- function(data) {
  fit <- lm(Count ~ Time, data = data)
  beta <- coefficients(fit)[[2]]
  alpha <- coefficients(fit)[[1]]
  tibble(beta = beta, alpha = alpha)
}

nested <- pedestrian %>%
  group_by_key() %>%
  slice(1:500) %>%
  group_by(Sensor) %>%
  nest()

nested
#> # A tibble: 4 x 2
#> # Groups:   Sensor [4]
#>   Sensor                        data              
#>   <chr>                         <list>            
#> 1 Birrarung Marr                <tbl_ts [500 × 4]>
#> 2 Bourke Street Mall (North)    <tbl_ts [500 × 4]>
#> 3 QV Market-Elizabeth St (West) <tbl_ts [500 × 4]>
#> 4 Southern Cross Station        <tbl_ts [500 × 4]>

nested <- nested %>%
  mutate(
    ols_model = map( 
      data,
      ~slide_vec(
        .x,
        ols_results,
        .before = 99,
        .complete = TRUE
      )
    ) 
  )

nested
#> # A tibble: 4 x 3
#> # Groups:   Sensor [4]
#>   Sensor                        data               ols_model         
#>   <chr>                         <list>             <list>            
#> 1 Birrarung Marr                <tbl_ts [500 × 4]> <tibble [500 × 2]>
#> 2 Bourke Street Mall (North)    <tbl_ts [500 × 4]> <tibble [500 × 2]>
#> 3 QV Market-Elizabeth St (West) <tbl_ts [500 × 4]> <tibble [500 × 2]>
#> 4 Southern Cross Station        <tbl_ts [500 × 4]> <tibble [500 × 2]>

slice(nested$ols_model[[1]], 98:102)
#> # A tibble: 5 x 2
#>    beta alpha
#>   <dbl> <dbl>
#> 1 NA     NA  
#> 2 NA     NA  
#> 3  4.25 175. 
#> 4  7.77 120. 
#> 5  9.39  93.5
```

**Comment by MatixR** [comment]
Thank you very much!
