### ISSUE TITLE
Tweak docs of `.before` and `.after` to avoid dot prefix confusion

### ISSUE THREAD

**Issue by gofford** [DavisVaughan/slider#155]
Hey @DavisVaughan 

Really liking the `slider` package. Wanted to raise the fact that some functions are using the `.prefix` notation for args whereas others aren't. This just caught me out when switching functions. 

Vast majority of functions are dot prefixed:

```
slide_vec(
  .x,
  .f,
  ...,
  .before = 0L,
  .after = 0L,
  .step = 1L,
  .complete = FALSE,
  .ptype = NULL
)
```

whereas the specialised functions aren't:

```
slide_mean(
  x,
  ...,
  before = 0L,
  after = 0L,
  step = 1L,
  complete = FALSE,
  na_rm = FALSE
)
```

Is this intentional? If so, the docs for the specialised functions need updating as they refer to args with the dot prefix when the args themselves are dot-free. e.g., from `R/summary-slide.R` (emphasis my own)

> **`before`** | [integer(1) / Inf]
> The number of values before or after the current element to include in the sliding window. Set to Inf to select all elements before or after the current element. Negative values are allowed, which allows you to "look forward" from the current element if used as the **`.before`** value, or "look backwards" if used as **`.after`**

**Comment by DavisVaughan** [comment]
This is intentional. The ones that have the `.` prefix pass the `...` through to `.f`, and the `.` prefix is used to minimize conflicts with any named arguments that may be passed through `...`.

The specialized variants only have `...` to require that all of the optional arguments be specified by name rather than position. They will error if you pass anything through them.

Regarding the docs, I ended up inheriting the documentation for `slide_mean()` from `slide()` (to minimize duplication), which is why you see `.before`. I'll tweak it to be a little more general so it is less confusing

**Comment by gofford** [comment]
Fair enough @DavisVaughan, and make complete sense in that context! I suspected it was intentional but wanted to raise it anyway, just in case. Thanks for the quick response and for the really useful package.

**Comment by DavisVaughan** [comment]
Hmm, turns out the `.` prefix is used a lot in the documentation of other parameters as well, such as those in `?slide_index_mean()`

Rather than either:
1. Duplicating a lot of documentation
2. Making the documentation harder to understand by replacing `.before` with the literal word "before"

I think I am just going to keep it the same, and hope that it doesn't cause too much confusion

**Comment by MikeJohnPage** [comment]
Hey, in case useful, I just wanted to flag that the lack of a dot prefix notation also caught me off guard, even after skimming through the docs. Thankfully the error message was informative enough that I was able to identify my mistake (using `.before` instead of `before` in `slide_index_mean()`).

Thanks for the great R package.
